CREATE TABLE [dbo].[UserTask]
(
	[UserTaskId] INT IDENTITY(1,1) NOT NULL, 
	[TaskId] INT NOT NULL REFERENCES Task(TaskId) ON DELETE  NO ACTION, 
	[UserId] INT NOT NULL REFERENCES UserProfile(UserId) ON DELETE CASCADE ON UPDATE CASCADE, 
	[StateId] INT NOT NULL REFERENCES TaskState(StateId) ON DELETE CASCADE

	CONSTRAINT [PK_UserTask] PRIMARY KEY ([UserTaskId])
)
